name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: ./CODEREVGENAI/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install testing libraries
        pip install httpx pytest

    - name: Basic Import Test
      working-directory: ./CODEREVGENAI/backend
      run: |
        # Verify that the app can be imported without errors
        python -c "from main import app; print('Application imported successfully')"

    - name: Build Docker Image
      run: docker build ./CODEREVGENAI/backend --file ./CODEREVGENAI/backend/Dockerfile --tag coderefine-backend:latest